steamKey: {{STEAM_KEY}}
mods:
- screepsmod-auth
- screepsmod-admin-utils
- screepsmod-server-stats
# - screepsmod-mongo  # You must install and start `mongodb` and `redis` before this mod will work
bots:
  bot: ./dist
serverConfig: # This section requires screepsmod-admin-utils to work
  welcomeText:  |
    <h1 style="text-align: center;">Performance server</h1>
env:
  backend:
    CLI_HOST: 0.0.0.0
